--创建寻宠网数据库forpet--
CREATE DATABASE IF NOT EXISTS `forpet` CHARACTER SET UTF8;
--使用forpet数据库--
USE forpet;
--创建微信用户信息表wechat_user--
--(用户编号id,用户openid,用户昵称nickname,性别sex,城市city,国家country,省份province,用户头像headimgurl,用户关注时间)--
CREATE TABLE IF NOT EXISTS wx_user(
	`id` INT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '用户编号',
	`openid` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户openid',
	`nickname` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '用户昵称',
	`sex` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '用户性别(1男性,2女性,0未知)',
	`city` VARCHAR(20) NOT NULL DEFAULT '广州' COMMENT '城市',
	`country` VARCHAR(20) NOT NULL DEFAULT '中国' COMMENT '国家',
	`province` VARCHAR(20) NOT NULL DEFAULT '广东' COMMENT '省份',
	`headimgurl` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '用户头像',
	`subscribe_time` VARCHAR(11) NOT NULL DEFAULT '' COMMENT '用户关注时间',
	`is_delete` SMALLINT(1) NOT NULL DEFAULT 0 COMMENT '用户是否删除,0未删除,1删除'
)ENGINE = MyISAM DEFAULT CHARSET = utf8mb4;
--创建流浪线索表wandering_clues--
CREATE TABLE IF NOT EXISTS wandering_clues(
	`id` INT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`openid` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户openid',
	`nickname` VARCHAR(20) NOT NULL DEFAULT '未知' COMMENT '宠物昵称',
	`sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '宠物性别',
	`description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '流浪描述',
	`imgsrc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '流浪动物现状',
	`pubdate` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '流浪线索发布时间',
	`publisher` VARCHAR(10) NOT NULL DEFAULT '匿名' COMMENT '联系人',
	`telephone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '联系方式',
	`location` VARCHAR(20) NOT NULL DEFAULT '广东,广州' COMMENT '位置'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建领养表adopt--
CREATE TABLE IF NOT EXISTS adopt(
	`id` INT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`openid` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户openid',
	`nickname` VARCHAR(20) NOT NULL DEFAULT '未知' COMMENT '宠物昵称',
	`sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '宠物性别',
	`cateid` INT(5) NOT NULL DEFAULT 0 COMMENT '分类ID',
	`age` TINYINT(5) NOT NULL DEFAULT 0 COMMENT '宠物年龄',
	`description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '领养要求',
	`imgsrc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '宠物照片',
	`pubdate` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '领养发布时间',
	`publisher` VARCHAR(10) NOT NULL DEFAULT '匿名' COMMENT '联系人',
	`telephone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '联系方式',
	`location` VARCHAR(20) NOT NULL DEFAULT '广东,广州' COMMENT '位置'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建寻回表retrieve--
CREATE TABLE IF NOT EXISTS retrieve(
	`id` INT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`openid` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户openid',
	`nickname` VARCHAR(20) NOT NULL DEFAULT '未知' COMMENT '宠物昵称',
	`sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '宠物性别',
	`cateid` INT(5) NOT NULL DEFAULT 0 COMMENT '分类ID',
	`age` TINYINT(5) NOT NULL DEFAULT 0 COMMENT '宠物年龄',
	`description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '宠物特征',
	`imgsrc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '宠物照片',
	`pubdate` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '寻回发布时间',
	`losetime` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '宠物丢失时间',
	`publisher` VARCHAR(10) NOT NULL DEFAULT '匿名' COMMENT '主人',
	`telephone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '主人联系方式',
	`location` VARCHAR(20) NOT NULL DEFAULT '广东,广州' COMMENT '位置'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建社区表--
CREATE TABLE IF NOT EXISTS community(
	`id` INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`pid` INT(10) UNSIGNED NOT NULL DEFAULT 0  COMMENT '宠物id',
	`location` VARCHAR(20) NOT NULL DEFAULT '广东,广州' COMMENT '位置',
	`imgsrc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '社区照片',
	`description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '社区描述',
	`pubdate` INT(10) NOT NULL DEFAULT 0 COMMENT '社区发布时间'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建社区点赞表--
CREATE TABLE IF NOT EXISTS community_praise(
	`id` INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '点赞编号',
	`userid` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户id',
	`cid` INT(10) UNSIGNED NOT NULL COMMENT '点赞社区id',
	`is_praise` SMALLINT(1) NOT NULL DEFAULT 0 COMMENT '是否点赞,0取消点赞,1点赞'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建社区评论表--
CREATE TABLE IF NOT EXISTS community_comment(
	`id` INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`userid` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户id',
	`cid` INT(10) UNSIGNED NOT NULL COMMENT '评论社区动态id',
	`content` VARCHAR(125) NOT NULL DEFAULT '' COMMENT '评论内容',
	`ctime` VARCHAR(10) NOT NULL DEFAULT '0' COMMENT '评论时间'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建宠物分类表pet_category--
CREATE TABLE IF NOT EXISTS pet_category(
	`id` INT(5) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '分类ID',
	`category_name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '分类名称',
	`pid` INT(5) NOT NULL DEFAULT 0 COMMENT '父类ID'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--添加分类数据--
INSERT INTO pet_category(id,category_name,pid) VALUES(DEFAULT,'小型宠物类',0),(DEFAULT,'两栖爬行类',0),(DEFAULT,'猫狗类',0),(DEFAULT,'水族类',0),(DEFAULT,'鸟类',0);
INSERT INTO pet_category(id,category_name,pid) VALUES(DEFAULT,'狗',3),(DEFAULT,'猫',3);
INSERT INTO pet_category(id,category_name,pid) VALUES(DEFAULT,'哈士奇',6),(DEFAULT,'藏獒',6),(DEFAULT,'贵宾犬',6),(DEFAULT,'边境牧羊犬',6),(DEFAULT,'吉娃娃',6),(DEFAULT,'德国牧羊犬',6),(DEFAULT,'秋田犬',6);
--创建养宠百科表encyclopedia--
CREATE TABLE IF NOT EXISTS encyclopedia(
	`id` INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '百科id',
	`title`	VARCHAR(60) NOT NULL DEFAULT '' COMMENT '百科标题',
	`description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '百科描述',
	`writer` CHAR(20) NOT NULL DEFAULT '' COMMENT '百科作者',
	`litpic` CHAR(100) NOT NULL DEFAULT '' COMMENT '百科图片',
	`pubdate` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '百科发布时间',
	`lastpost` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '上一次百科更新时间',
	`click` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '百科点击数',
	`keywords` CHAR(30) NOT NULL DEFAULT '' COMMENT '百科关键词',
	`goodpost` MEDIUMINT(8) NOT NULL DEFAULT '0' COMMENT '百科点赞数',
	`badpost` MEDIUMINT(8) NOT NULL DEFAULT '0' COMMENT '百科差评数',
	`body` MEDIUMTEXT COMMENT '百科内容',
	`is_delete` MEDIUMINT(1) NOT NULL DEFAULT '0' COMMENT '百科是否删除,0代表没删,1代表已删'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建养宠百科收藏表--
CREATE TABLE IF NOT EXISTS knowledge_collect(
	`id` INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '收藏编号',
	`openid` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户openid',
	`kid` INT(10) UNSIGNED NOT NULL COMMENT '百科id'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建好友表friends--
CREATE TABLE IF NOT EXISTS friends(
	`id` MEDIUMINT(8) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`uid` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
	`fid` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '好友id'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建好友申请表friends_request--
CREATE TABLE IF NOT EXISTS friends_request(
	`id` MEDIUMINT(8) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`uid` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '被申请用户id',
	`rid` INT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '好友申请人id',
	`content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '申请内容'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建好友聊天表friends_chat--
CREATE TABLE IF NOT EXISTS friends_chat(
	`id` INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	`sender` CHAR(16) NOT NULL DEFAULT '' COMMENT '发送者',
	`receiver` CHAR(16) NOT NULL DEFAULT '' COMMENT '接收者',
	`receiverRead` TINYINT(4) DEFAULT 0 COMMENT '接收者是否已读',
	`chat_time` INT(10) UNSIGNED NOT NULL DEFAULT 0  COMMENT '聊天时间',
	`content` TEXT NOT NULL  COMMENT '发送内容'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;
--创建宠物表pets--
CREATE TABLE IF NOT EXISTS pets(
	id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
	userid INT(20) UNSIGNED NOT NULL COMMENT '用户编号',
	nickname VARCHAR(25) NOT NULL DEFAULT '' COMMENT '宠物昵称',
	sex TINYINT(8) NOT NULL DEFAULT 1 COMMENT '宠物性别(1公,2母,0未知)',
	headimgurl VARCHAR(255) NOT NULL DEFAULT '' COMMENT '宠物头像',
	cateid TINYINT(8) NOT NULL DEFAULT 1 COMMENT '宠物类别',
	birthday VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '宠物出生日期',
	weight TINYINT(3) NOT NULL DEFAULT 0 COMMENT '宠物体重'
)ENGINE = MyISAM DEFAULT CHARSET = UTF8;